name: Deploy

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Copy repository content to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: '.'
          target: 'node/personal'
          strip_components: 1

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd node/personal
            npm ci
            npm run build
            PM2_HOME=/home/voqse-node/pm2 pm2 delete index.js
            PM2_HOME=/home/voqse-node/pm2 pm2 start index.js
